DROP TABLE IF EXISTS score;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS creators_games;
DROP TABLE IF EXISTS game_tags;
DROP TABLE IF EXISTS stats;
DROP TABLE IF EXISTS screenshots;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS games;
DROP TABLE IF EXISTS creators;


CREATE TABLE creators(
	id_creator INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(48) NOT NULL,
	username VARCHAR(16) NOT NULL,
	password CHAR(32) NOT NULL,
	email VARCHAR(32) NOT NULL,
	image VARCHAR(16),
	description TEXT
);
CREATE TABLE games(
	id_game INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(32) NOT NULL,
	`link` VARCHAR(128) NOT NULL,
	header VARCHAR(16),
	price DECIMAL(5, 2),
	trailer VARCHAR(128)
);
CREATE TABLE tags(
	id_tag INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(32) NOT NULL,
	color CHAR(6) NOT NULL
);
CREATE TABLE screenshots(
	id_screenshot INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	image VARCHAR(16) NOT NULL,
	description VARCHAR(128),
	id_game INT UNSIGNED NOT NULL,
	FOREIGN KEY (id_game) REFERENCES games(id_game)
);
CREATE TABLE stats(
	id_stat INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	views INT UNSIGNED DEFAULT 0,
	downloads INT UNSIGNED DEFAULT 0,
	likes INT UNSIGNED DEFAULT 0,
	id_game INT UNSIGNED NOT NULL UNIQUE,
	FOREIGN KEY (id_game) REFERENCES games(id_game)
);
CREATE TABLE game_tags(
	id_game_tag INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id_game INT UNSIGNED NOT NULL,
	id_tag INT UNSIGNED NOT NULL,
	FOREIGN KEY (id_game) REFERENCES games(id_game),
	FOREIGN KEY (id_tag) REFERENCES tags(id_tag)
);
CREATE TABLE creators_games(
	id_creator_game INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id_creator INT UNSIGNED NOT NULL,
	id_game INT UNSIGNED NOT NULL UNIQUE,
	FOREIGN KEY (id_creator) REFERENCES creators(id_creator),
	FOREIGN KEY (id_game) REFERENCES games(id_game)
);
CREATE TABLE comments(
	id_comment INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	coment_text TEXT NOT NULL,
	id_creator INT UNSIGNED NOT NULL,
	id_game INT UNSIGNED NOT NULL,
	FOREIGN KEY (id_creator) REFERENCES creators(id_creator),
	FOREIGN KEY (id_game) REFERENCES games(id_game)
);
CREATE TABLE score(
	id_comment INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	score INT NOT NULL,
	date_time DATETIME NOT NULL,
	id_creator INT UNSIGNED NOT NULL,
	id_game INT UNSIGNED NOT NULL,
	FOREIGN KEY (id_creator) REFERENCES creators(id_creator),
	FOREIGN KEY (id_game) REFERENCES games(id_game)	
);
